### ISSUE TITLE
Problème d'affichage du profil utilisateur depuis l'onglet Participants d'un cours

### ISSUE THREAD

**Issue by Pedagotheque** [call-learning/moodle-theme_imtpn#10]
Bonjour Laurent,
Nous avons constaté un problème d'affichage du profil utilisateur, lorsque l'on y accède depuis l'onglet _Participants_ d'un cours (cf. capture ci-jointe).
Cordialement
__
Camille
![image](https://user-images.githubusercontent.com/69036392/125475440-c95f0df9-0422-4c3a-ae89-4b9d0d59b42d.png)

**Comment by laurentdavid** [comment]
Bonjour Camille,

Est-ce que le $CFG->customscript a été mis en place ? Si ce n'est pas le cas, je pense que le problème vient de là.

Laurent

**Comment by laurentdavid** [comment]
Je confirme, c'est effectivement un soucis lié à l'absence de la configuration ci-dessous dans le fichier config.php

$CFG->customscripts = dirname(__FILE__) . '/theme/imtpn/customscripts/';

**Comment by Pedagotheque** [comment]
Bonjour Laurent,
C'est noté. Merci beaucoup.
Camille
