### ISSUE TITLE
Créer / quitter un groupe sur le mur pédagogique du thème IMTPN

### ISSUE THREAD

**Issue by Pedagotheque** [call-learning/moodle-theme_imtpn#11]
Bonjour Laurent,
Je me permets de te soumettre cette interrogation: comment quitter ou créer un groupe sur le mur pédagogique du thème IMTPN (même avec le rôle "Etudiant")?
Cordialement
__
Camille

**Comment by laurentdavid** [comment]
Bonjour,

Sur la problématique de quitter, effectivement il y avait un manque. Je viens de rajouter le bouton et le process pour quitter un groupe.
A propos de créer un groupe, il faut avoir la capacité de gérer les groupes (moodle/course:managegroups dans le cours). D'après moi cette capacité n'est pas donnée par défaut aux étudiants donc soit il faut le rajouter au rôle ou en créer un spécial pour permettre de créer un groupe sur ce cours.

**Comment by Pedagotheque** [comment]
Bonjour Laurent,
Je mettrai en place une dérogation de permission pour le rôle étudiant, dans le cours concerné uniquement. Merci pour l'information!
Camille

**Comment by Pedagotheque** [comment]
Bonjour Laurent,

Je me permets de te signaler de nouveaux dysfonctionnements dans le mur Pédagogique:
- Le bouton "Quitter le groupe" semble ne pas fonctionner: l'utilisateur reste membre du groupe malgré le message de confirmation.
- Le message de confirmation lorsque l'on quitte un groupe n'est pas traduit.
- En accordant une dérogation de permission au rôle étudiant pour "moodle/course:managegroups" dans le cours, le bouton "Activer le mode édition" apparaît même s'il semble ne rien faire lorsque l'on clique dessus.
__
Camille

**Comment by laurentdavid** [comment]
Enseignant démo

**Comment by laurentdavid** [comment]
Bonjour Camille,

Bonne nouvelle, c'était une erreur (bête). Je corrige et je teste bien. Tu auras une nouvelle version très bientôt.

Laurent
