### ISSUE TITLE
Gestion des groupes privés sur le mur pédagogique du thème IMTPN

### ISSUE THREAD

**Issue by Pedagotheque** [call-learning/moodle-theme_imtpn#12]
Bonjour Laurent,

Sur le mur pédagogique certains groupes sont privés (accessibles avec une clef de groupe), mais on quand même le rejoindre sans saisir de clef lorsque l'on a le rôle "Etudiant". 

Cordialement
__
Camille

**Comment by laurentdavid** [comment]
Effectivement cela n'était pas pris en compte. Cela vient d'être corrigé.

**Comment by Pedagotheque** [comment]
Top! Merci Laurent.
