### ISSUE TITLE
Gestion des enseignants non éditeurs

### ISSUE THREAD

**Issue by Pedagotheque** [call-learning/moodle-theme_imtpn#13]
Bonjour Laurent,

Je ne sais pas si ce 1er sujet relève de ce thème-ci ou de la surcouche CL: les enseignants non éditeurs n'ont pas le "teacher dashboard". Ce n'est, en soi, pas gênant car il est remplacé par la "roue crantée" standard de Moodle.

En revanche, dans le cadre du thème IMTPN, l'absence du menu latéral gauche fait que les enseignants et enseignants non éditeurs surtout (puisqu'il semble qu'ils ne peuvent pas inscrire des utilisateurs) n'ont plus d'accès aux participants du cours. Peut-on ajouter une entrée dans le menu utilisateur (avec le carnet de notes et les événements du cours)?

Merci!
__
Camille

**Comment by laurentdavid** [comment]
Le critère pour l'apparition du menu crantée était fixée sur les droits d'édition de cours. J'ai maintenant repris le code qui permettant d'afficher la roue crantée qui est un peu différente, donc le menu devrait apparaître maintenant pour les enseignants non éditeurs aussi.
