### ISSUE TITLE
Impossibilité de revenir au cours depuis la page "Participants"

### ISSUE THREAD

**Issue by Pedagotheque** [call-learning/moodle-theme_imtpn#16]
Bonjour Laurent,

Depuis la page "Participants" d'un cours, il manque le fil d'ariane et éventuellement un bouton pour revenir au cours. Il est donc "impossible" de revenir au cours depuis cette page, même pour un administrateur.

Cordialement
__
Camille

**Comment by laurentdavid** [comment]
Bonjour,

En fait il s'agit d'un CSS additionnel qui cache cette partie de page. Je vais clore ce bug et t'envoyer les infos.

Laurent
